version: "3.6"

services:
  rabbitmq:
    image: "rabbitmq:3.6-management-alpine"
    ports:
      # The standard AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    environment:
      AMQP_URL: "amqp://rabbitmq?connection_attempts=5&retry_delay=5"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - network

networks:
  network:
    driver: bridge
